"""All done

Revision ID: 8f6132bf8624
Revises: 
Create Date: 2023-05-21 22:25:01.368970

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '8f6132bf8624'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
